export default class DecisionEngine {
  constructor(toolManager) {
    this.toolManager = toolManager; // To be implemented in Phase 5
  }

  async executePlan(planResult) {
    console.log(`[DecisionEngine] Executing plan with ${planResult.plan?.length || 0} steps`);
    
    const results = [];
    
    // Iterate over the tool calls generated by the planner
    if (planResult.toolCalls && planResult.toolCalls.length > 0) {
      for (const call of planResult.toolCalls) {
        const { toolName, args } = call;
        console.log(`[DecisionEngine] Executing tool: ${toolName} with args: ${JSON.stringify(args)}`);
        try {
          const result = await this.toolManager.execute(toolName, args || {});
          results.push({ tool: toolName, status: 'success', data: result });
        } catch (error) {
          console.error(`[DecisionEngine] Tool failed: ${error.message}`);
          results.push({ tool: toolName, status: 'failed', error: error.message });
        }
      }
    } else {
      console.log('[DecisionEngine] No tools requested in plan.');
    }
    
    return results;
  }
}
